apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: krithikv/flask-worker-app:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "src/worker.py"]
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: PYTHONUNBUFFERED
              value: "1"
