apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        # ── Primary Redis container ───────────────────────────
        - name: redis
          image: redis:7.2-alpine
          # Force an automatic RDB snapshot every 60 s if at least
          # 1 write occurred, to keep dump.rdb reasonably current.
          args: ["--save", "60", "1", "--loglevel", "warning"]
          volumeMounts:
            - name: redis-storage
              mountPath: /data
        # ── Side‑car backup container ─────────────────────────
        - name: redis-backup
          image: busybox:1.36
          # Copies /data/dump.rdb to timestamped backups every hour
          command:
            - /bin/sh
            - -c
            - |
              echo "[backup] side‑car started";
              while true; do
                ts=$(date +%Y%m%d-%H%M%S);
                if [ -f /data/dump.rdb ]; then
                  cp /data/dump.rdb /data/backup-${ts}.rdb;
                  # keep only the 24 most recent snapshots
                  ls -1t /data/backup-*.rdb | tail -n +25 | xargs -r rm -f;
                  echo "[backup] snapshot copied at ${ts}";
                fi
                sleep 3600;
              done
          volumeMounts:
            - name: redis-storage
              mountPath: /data
